
project 'ProjectB.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectB' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'FMDB', '~> 2.6'
pod 'AFNetworking', '~> 3.1'
pod 'MJRefresh', '~> 3.1'
pod 'MBProgressHUD', '~> 1.0'
pod 'MMDrawerController', '~> 0.6'
pod 'SDWebImage', '~> 3.8'
pod 'WMPageController', '~> 1.9'
pod 'Masonry', '~> 1.0'
  # Pods for ProjectB
  

end
